Fix missing translations - 2
Fix name '_' is not defined error

Traceback (most recent call last):
  File "/app/share/tomatillo/tomatillo/main.py", line 74, in on_about_action
    about.set_translator_credits(_("translator-credits"))
                                 ^
NameError: name '_' is not defined